### PR TITLE
Fix dependency in PR #78

### PR DESCRIPTION
**Pull request by florianb**

### CODE REVIEW

**Comment by sindresorhus** [comment]
No need to do a PR for small stuff like this. Just commit directly ;)

**Comment by sindresorhus** [comment]
And use `git pull --rebase`, not `git pull`.

**Comment by florianb** [comment]
I work with Github Desktop, it is the second time now it messes a PR up. I guess i'll switch back to Tower or cli. 😞

**Comment by Arcanemagus** [comment]
Check out GitKraken, I've been using it for a few months now over GitHub Desktop, it's a _much_ nicer interface :wink:.

**Comment by florianb** [comment]
Good hint - i'll give it a try. I sticked to Github Desktop for a while because collecting hunks in commits was so easy to do.

**Pull request closed without merging**
