### PR TITLE
Fixes EOL replace: Reverts #51, Fixes #56, Fixes #54, Fixes #50

### LINKED ISSUE #50: atom-editorconfig changes indentation after indentation-indicator reads it
This leads to indentation-indicator incorrectly displaying the actual indentation until I switch to another tab and back.

The indentation-indicator author suggests atom-editorconfig is not using the Atom API properly:

https://github.com/lee-dohm/indentation-indicator/issues/15#issuecomment-136217033

### LINKED ISSUE #54: Enabling editorconfig plugin scrambles my files
After upgrade to atom 1.1, I got all my files in editor somehow scrambled and realigned.
When analyzing the issue, I have figured out that this happens only when I enable the `editorconfig` package (if the package is disabled, it doesn't happen).

Here is a screenshot of my file with `editorconfig` disabled:
atom-pre

And again with `editorconfig` package enabled:
atom-post

My `.editorconfig` file is:

		# EditorConfig is awesome: http://EditorConfig.org

		# top-most EditorConfig file
		root = true

		# Unix-style newlines with a newline ending every file
		[*]
		end_of_line = lf
		insert_final_newline = true
		indent_style = tab
		indent_size = 4
		charset = utf-8

		# 4 space indentation
		[*.{py}]
		indent_style = space
		indent_size = 4

		# 2 space indentation
		[*.{js,jsx}]
		indent_size = 2
		indent_style= space

		# Indentation override for all JS under lib directory
		#[lib/**.js]
		#indent_style = space
		#indent_size = 2

		# Matches the exact files either package.json or .travis.yml
		#[{package.json,.travis.yml}]
		#indent_style = space
		#indent_size = 2

### LINKED ISSUE #56: Slow at opening lagre files
Hello

After installing editorconfig I noticed that when opening a CSS file with over 3500 lines it takes about 3-4 secs before the I can start edit the file and before language highlight highlights the file. During the 3-4 secs Atom completely freezes.

When there is no editorconfig in my project this issue do not occur even with editorconfig enabled.

Occurs in Atom 1.2.4 and Atom 1.3.0-beta6 with only editorconfig enabled.

Here is my editorconfig:
````
# top-most EditorConfig file
root = true

# All files configuration
[*]
end_of_line = lf
insert_final_newline = true
charset = utf-8
trim_trailing_whitespace = true

# PHP Configuration
[*.php]
indent_style = space
indent_size = 4

# JS configuration
[*.js]
indent_style = space
indent_size = 2

# CSS configuration
[*.css]
indent_style = space
indent_size = 2

# SCSS configuration
[*.scss]
indent_style = space
indent_size = 2
````

### PR DESCRIPTION
**Pull request by dbachko**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you use https://github.com/sindresorhus/atom-set-text here instead? It also preserves cursor/scroll position, so #51 wouldn't be reverted.

**Comment by dbachko** [comment]
Your proposal does not work because:

Original text-buffer's api [setTextInRange](https://github.com/atom/text-buffer/blob/master/src/text-buffer.coffee#L624) function has an option * `normalizeLineEndings` (optional) {Boolean} (default: true) so there is no need to use custom implementation of #51.

It takes 23s to open the file with ~12000 lines vs 1.10s with setTextInRange.

issue_51
pull_61

**Comment by sindresorhus** [comment]
> Original text-buffer's api setTextInRange function has an option * normalizeLineEndings (optional) {Boolean} (default: true)

We don't want to normalize line endings, we want to enforce a certain type of line endings. Your change does not do that. Why not just `text.replace(/\r?\n/g, preferredLineEnding)` and pass it to`atom-set-text`?

**Comment by dbachko** [comment]
Take a look here sir(it enforce a certain type of line endings as you want):

crlf-endings
lf-ending

**Comment by sindresorhus** [comment]
> Because there is the official more efficient(22 times faster) implementation of what you want to implement by yourself. Why not use api?

Looking at your screenshots, the measurement is with `backwardsScanInRange`, not what I'm proposing.

I'm not against using the API. I'm against having duplicated code. I prefer to solve the issue once and be able to reuse it everywhere. Your solution also does not preserve scroll/cursor position AFAIK.

If `setTextInRange` is faster than `text.replace(/\r?\n/g, preferredLineEnding)` and passing it to `atom-set-text`, I would be happy to switch to it in `atom-set-text`.

**Comment by dbachko** [comment]
It is your second statement that something is not. Did you try?

**Comment by sindresorhus** [comment]
I'm not sure what you're asking.

**Comment by dbachko** [comment]
How about this? Performance is the same.

**Comment by sindresorhus** [comment]
@dbachko Perfect! Exactly what I was thinking. Thank you :)

**Pull request closed without merging**
