### PR TITLE
Fix deprecations

### PR DESCRIPTION
**Pull request by ArnaudRinquin**
Just fix some `atom 1.0` deprecations.

### CODE REVIEW

**Comment by kevva** [comment]
Should wait with merging this until 1.0 is released.

**Comment by ArnaudRinquin** [comment]
Well, these calls already are deprecated and aren't going to be _un-deprecated_. 
So I think it doesn't hurt to merge them right away.

**Comment by sindresorhus** [comment]
Where are those deprecation documented?

Especially the `scoped-properties/atom-editorconfig.cson → settings/atom-editorconfig.cson` one.

**Comment by ArnaudRinquin** [comment]
These are visible through the Deprecation Cop. Not sure where else they are
documented.

**Comment by ArnaudRinquin** [comment]
Actually, there is [a guide](https://atom.io/docs/latest/upgrading-to-1-0-apis-upgrading-your-package) but it says nothing about the `styles` folder.

**Comment by jerone** [comment]
Latest upgrade documentation always available here: https://atom.io/docs/latest/upgrading/upgrading-your-package

**Pull request closed without merging**
