### PR TITLE
Unpublish banner image

### PR DESCRIPTION
**Pull request by Alhadis**
Minor fix to improve the package's filesize (shaving off ~1.6 MBs). Basically, this image is now being loaded from a specific commit, instead of the master branch:

Ideally, we'd be using `.npmignore` to exclude the image from publication, but Atom's package manager has no support for this feature... so whatever the branch holds at the time of release is what gets tarballed.

### CODE REVIEW

**Comment by gorriecoe** [comment]
You could use .gitattributes to ignore files during publication.

```
* text=auto
*.js text eol=lf
/.gitignore export-ignore
/.gitattributes export-ignore
/.editorconfig export-ignore
/fievel-mousekewitz48.gif export-ignore
```

**Comment by Alhadis** [comment]
@gorriecoe That only works for `git archive`. NPM and APM work differently.

**Comment by gorriecoe** [comment]
@Alhadis This works. I have used the same approach in https://github.com/gorriecoe/atom-silverstripe.

**Comment by Alhadis** [comment]
Well, I'll be fucked... it does too.

Makes me wonder why the hell we even need `.npmignore` files, then.

**Pull request closed without merging**
